---
name: Test Assignment 20240412

on:
  push:
    branches:
      - submit/**
    paths:
      - assignments/20240412/*.py

env:
  PYTHONUNBUFFERED: '1'
  FORCE_COLOR: '1'
  PYTHON_VERSION: '3.12'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.test.txt
      - name: Install test dependencies
        run: pip install -r requirements.test.txt
      - name: Run tests
        run: pytest assignments/20240412 -vv
